# Schnellsuchfeld - Prototyp
:toc: preamble
:toc-title: Übersicht


Das SchnellsuchfeldBHH ist ein Prototyp für den Auswahlfilter für ein kamerales Haushaltsaufstellungsverfahren.

Eine https://schnellsuchfeldbhh.netlify.app/[lauffähige Version] wird via Netlify zur Verfügung gestellt.

Eine <<docs/anleitung.adoc#,Anleitung>> findet sich im /docs-Unterverzeichnis.

## Alternative 1: Installation auf eigenem Rechner

### Voraussetzungen

Der Prototyp läuft auf https://nodejs.org/de/[Node.js]. Node.js muss installiert sein.

Um den Quellcode herunterzuladen, braucht man https://git-scm.com/[git]. Auch das muss installiert sein.

### Herunterladen

In einer Terminal/Shell/Kommandozeilenumgebung gibt man zum Herunterladen Folgendes ein:

  git clone https://github.com/fritzminor/schnellsuchfeldbhh.git


### Installation der Bibliotheken, von dem der Prototyp abhängt

  cd schnellsuchfeldbhh/
  npm install 

### Alternative 1.a) Starten des Entwicklungsservers
  
  cd schnellsuchfeldbhh/
  npm run start

### Alternative 1.b) Produktiv bauen

Alternativ zum langsameren Entwicklungsserver kann man den Prototyp auch folgendermaßen bauen:

  cd schnellsuchfeldbhh/
  npm run build

Das Ergebnis kann man mit einem beliebigen Webserver wie Apache oder Nginx ausliefern oder aber folgendermaßen:

  cd schnellsuchfeldbhh/
  npx serve -s build/

## Alternative 2: Einrichten einer Entwicklungsumgebung auf codesandbox.io

Alternativ zur Installation auf einem eigenen Rechner kann man sich einen ersten Eindruck vom Quellcode in einer Online-Entwicklungsumgebung verschaffen. Dazu kann man unter https://codesandbox.io/ sich ein Benutzerkonto anlegen und dann mit "New Sandbox" -> "Import Project" -> "Import from Github" das Projekt "https://github.com/fritzminor/schnellsuchfeldbhh" importieren.

Noch schneller geht das mit 
https://githubbox.com/fritzminor/schnellsuchfeldbhh .

## Demonstration

* Aufrufen von https://schnellsuchfeldbhh.netlify.app/
* Beim leeren Suchfeld werden alle Haushaltsstellen des
  Bearbeiters angezeigt (hier grundsätzlich die Einzelpläne des Bundespräsidenten -Epl 01- und des Bundestags -Epl 02-).
* Man sieht 
  - Titel (mit FKZ) Zweck, Betrag 2021
  - Summe Einnahmen und Ausgaben
  - Nach welchen Suchkriterien gefiltert wird.
  
* Eingrenzen auf Epl 02 Bundestag mit 
  - _02_
  - _Epl:02_
  - _Epl:2_
* Suche nach Bezüge des Bundespräsidenten
  - _Präsident_
  - _4_
  - _Grp:4_
* Kombination: nur im Epl 01 die Personalausgaben (Hauptgruppe 4)
  - _01 Grp:4_
* Suche nach Titeln mit Beträgen über 1 Mio. €
  - _1000_ => Vorschlag "Soll1:1000"
  - _Soll1:1000-_
* Suche nach Titeln mit Beträgen zwischen 1 und 2 Mio. €
  - _Soll1:1000-2000_

* Tipphilfe beim Stehenlassen des Mauszeigers auf Suchfeld

* Suche nach Ausgaben im Epl:02, jedoch ohne Personalausgaben
  - _02 -4_ - Beachte das Leerzeichen vor dem Minuszeichen.




## Weitere mögliche Verbesserungen

Das folgende sind Ideen. Da es sich aber nur um einen Prototyp handelt, kann es gut sein, dass es beim Ideenstand bleibt.

- TG:text wird bisher im Vorschlägebereich weder erläutert noch vorgeschlagen, Anleitung muss angepasst werden.
- Bei fullTextMatch sollte Token hervorgehoben werden (notfalls nur im helptext etwa so "'Epl:13' in 'Grp:5 Epl:13' führt zu Suche nach ...", wobei "Epl:13" beides Mal unterstrichen wird)
- Weitere Suchvorschläge, wenn Grp:\d, nämlich Grp:$1\d und Grp:$1\d\d
- A und E als Schnelleingrenzung auf Ausgaben oder Einnahmen
- Ignoriere Leerzeichen vor schließender Klammer



## Weiterentwicklung

Der Prototyp kann frei unter der MIT-Lizenz genutzt werden. Verbesserungen sind willkommen, insbesondere via Pull Requests. Ein paar Hinweise zum Code finden sich  in https://github.com/fritzminor/schnellsuchfeldbhh/blob/main/docs/entwicklung.adoc .

Feedback bitte via https://github.com/fritzminor/schnellsuchfeldbhh/issues[GitHub-Issue].


Viel Spaß und Erfolg!